### ISSUE TITLE
Classifier service does not allow schema without LABEL

### ISSUE THREAD

**Issue by kmaehashi** [jubatus/jubakit#40]
Schema of Classifier service does not allow creating schema without LABEL column.

```py
>>> from jubakit.classifier import Schema
>>> Schema({"name": Schema.STRING})
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/kenichi/Development/jubakit/jubakit/classifier.py", line 21, in __init__
    self._label_key = self._get_unique_mapping(mapping, fallback, self.LABEL, 'LABEL')
  File "/Users/kenichi/Development/jubakit/jubakit/base.py", line 123, in _get_unique_mapping
    raise RuntimeError('{0} key must be specified in schema'.format(name))
RuntimeError: LABEL key must be specified in schema
```

It was an intended spec at design time, but I think this restriction was unneeded.
It is rather inconvenient when using different Datasets for training and classification; Schema of classification Dataset does not require LABEL column.

**Comment by kmaehashi** [comment]
Fixed via #57
