### ISSUE TITLE
Non-static Datasets does not allow automatic Schema prediction

### ISSUE THREAD

**Issue by kmaehashi** [jubatus/jubakit#41]
Non-static Datasets does not allow automatic Schema prediction.  It is inconvenient and should be fixed.

```py
>>> from jubakit.loader.array import ZipArrayLoader
>>> from jubakit.anomaly import Dataset
>>> 
>>> loader = ZipArrayLoader(k1=[1,4], k2=[2,5], k3=[3,6])
>>> ds = Dataset(loader, static=False)
>>> for x in ds: print(x)
... 
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/kenichi/Development/jubakit/jubakit/base.py", line 393, in __iter__
    yield (self._index, self._schema.transform(row))
AttributeError: 'NoneType' object has no attribute 'transform'
```

**Comment by shiodat** [comment]
Fixed via #64.
