### ISSUE TITLE
Exception in service destructor

### ISSUE THREAD

**Issue by kmaehashi** [jubatus/jubakit#48]
When running Service class is destroyed while terminating python process, sometimes the following message is displayed.  We should avoid seeking already-closed log buffer.

```
Exception ignored in: <bound method BaseService.__del__ of <jubakit.classifier.Classifier object at 0x7f219fbd8320>>
Traceback (most recent call last):
  File "/home/jubatus/Development/jubakit/jubakit/base.py", line 422, in __del__
    backend.stop()
  File "/home/jubatus/Development/jubakit/jubakit/base.py", line 595, in stop
    self._logbuf.seek(0)
  File "/home/jubatus/.pyenv/versions/3.5.1/lib/python3.5/tempfile.py", line 483, in func_wrapper
    return func(*args, **kwargs)
ValueError: seek of closed file
```

**Comment by kmaehashi** [comment]
Fixed via #54
